spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/book_management_system?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

